import { z } from 'zod';

// Shared validation schema used by both frontend and backend.
export const RawGameStateSchema = z.object({
  id: z.string().uuid(),
  days_remaining: z.number().default(30),
  action_points: z.number().default(5),
  wall_health: z.number().default(100),
  defense_power: z.number().default(1000),
  gold: z.number().min(0),
  wood: z.number().min(1000),
  iron: z.number().min(250),
  stone: z.number().min(0),
  food: z.number().min(50000),
  gunpowder: z.number().default(500),
  swords: z.number().min(0).default(600),
  spears: z.number().min(0).default(2500),
  bows: z.number().min(0).default(400),
  soldiers: z.number().default(1200),
  volunteers: z.number().default(800),
  wounded: z.number().default(0),
  pop_garrison: z.number().default(2100),
  german_cannonmasters: z.number().default(6),
  women_of_eger: z.number().default(100),
  hussars: z.number().default(0),
  heroes: z.number().default(6),
  archers: z.number().min(0).default(0),
  day: z.number().int().min(1),
  morale: z.number().min(0).max(100),
  updated_at: z.string(),
  gold_rate: z.number().min(0),
  wood_rate: z.number().min(0),
  iron_rate: z.number().min(0),
  stone_rate: z.number().min(0),
  food_rate: z.number().min(0),
});

export const GameStateSchema = RawGameStateSchema.transform((db) => ({
  status: {
    daysRemaining: db.days_remaining,
    actionPoints: db.action_points,
    wallHealth: db.wall_health,
    defensePower: db.defense_power,
  },
  resources: {
    gold: db.gold,
    wood: db.wood,
    iron: db.iron,
    stone: db.stone,
    food: db.food,
    swords: db.swords,
    spears: db.spears,
    bows: db.bows,
    gunpowder: db.gunpowder,
  },
  population: {
    pop_garrison: db.pop_garrison,
    volunteers: db.volunteers,
    women_of_eger: db.women_of_eger,
    wounded: db.wounded,
  },
  military: {
    soldiers: db.soldiers,
    archers: db.archers,
    hussars: db.hussars,
    german_cannonmasters: db.german_cannonmasters,
    heroes: db.heroes,
  },
  day: db.day,
  morale: db.morale,
  updated_at: new Date(db.updated_at),
  gold_rate: db.gold_rate,
  wood_rate: db.wood_rate,
  iron_rate: db.iron_rate,
  stone_rate: db.stone_rate,
  food_rate: db.food_rate,
}));

export type GameState = z.infer<typeof GameStateSchema>;
